{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "threatorbit.fullname" . }}-secrets
  labels:
    {{- include "threatorbit.labels" . | nindent 4 }}
type: Opaque
stringData:
  appApiKey: {{ .Values.secrets.appApiKey | quote }}
  adminApiKey: {{ .Values.secrets.adminApiKey | quote }}
  jwtSecret: {{ .Values.secrets.jwtSecret | quote }}
  adminEmail: {{ .Values.secrets.adminEmail | quote }}
  adminPassword: {{ .Values.secrets.adminPassword | quote }}
  otxApiKey: {{ .Values.secrets.otxApiKey | quote }}
  virustotalApiKey: {{ .Values.secrets.virustotalApiKey | quote }}
  openctiApiKey: {{ .Values.secrets.openctiApiKey | quote }}
  databaseUrl: {{ .Values.postgres.url | quote }}
{{- end }}
